Repository Guzzing/Studay_Client, pull requests merged in 2023-11, with the labels that each got.

#66 feat: 메인페이지 생성
  src/assets/icon/Add.svg
  src/components/common/informationBox/InformationBox.tsx
  src/components/common/spacing/Spacing.tsx
  src/pages/HomePage.tsx
  src/pages/home/HomePage.tsx
  src/routes/index.tsx
  src/styles/index.css
Labels: feat

#58 input 컴포넌트 구현
  src/App.tsx
  src/components/common/button/Button.tsx
  src/components/common/inputbox/input/Input.stories.tsx
  src/components/common/inputbox/input/Input.tsx
  src/components/common/inputbox/input/InputType.ts
  src/components/common/inputbox/select/Select.stories.tsx
  src/components/common/inputbox/select/Select.tsx
  src/components/common/inputbox/select/SelectType.ts
Labels: feat

#69 feat: 아이 정보 보기, 수정하기 페이지 구현
  src/components/common/header/Header.tsx
  src/components/common/informationBox/InformationBox.tsx
  src/components/common/listRow/ListRow.tsx
  src/components/common/navigationbar/NavigationBar.tsx
  src/components/common/navigationbar/constants.ts
  src/components/common/profile/Profile.tsx
  src/components/common/profile/ProfileType.ts
  src/pages/EditChildren/EditChildren.tsx
  src/pages/home/HomePage.tsx
  src/routes/index.tsx
Labels: feat

#70 컴포넌트 className 업데이트
  src/App.tsx
  src/components/common/header/Header.tsx
  src/components/common/informationBox/InformationBox.tsx
  src/components/common/inputbox/input/Input.tsx
  src/components/common/inputbox/select/Select.tsx
  src/components/common/inputbox/select/SelectType.ts
  src/components/common/scheduleBox/ScheduleBox.tsx
Labels: feat

#73 feat: API 공통 파일 구현
  src/api/index.ts
Labels: feat

#79 Refac : Figma 스타일 가이드에 맞게 코드 개선
  .eslintrc.cjs
  .prettierrc
  src/components/BottomSheet/BottomSheetContent.tsx
  src/components/BottomSheet/BottomSheetHeader.tsx
  src/components/common/accordion/Accordion.tsx
  src/components/common/bottomsheet/BottomSheet.tsx
  src/components/common/header/Header.tsx
  src/components/common/index.tsx
  src/components/common/informationBox/InformationBox.tsx
  src/components/common/inputbox/input/Input.tsx
  src/components/common/inputbox/select/Select.tsx
  src/components/common/listRow/ListRow.tsx
  src/components/common/modal/InputModal.tsx
  src/components/common/navigationbar/NavigationBar.tsx
  src/components/common/profile/Profile.tsx
  src/components/common/scheduleBox/ScheduleBox.stories.tsx
  src/components/common/scheduleBox/ScheduleBox.tsx
  src/components/common/selectweek/SelectWeek.tsx
  src/components/common/stepquestion/constants.ts
  src/styles/index.css
  tailwind.config.js
Labels: refac

#80 feat: 아이 프로필 수정하기 페이지
  package-lock.json
  package.json
  src/assets/icon/Logo.svg
  src/assets/icon/Spinner.svg
  src/assets/icon/index.tsx
  src/assets/img/logo100.png
  src/assets/img/logo150.png
  src/assets/img/logo50.png
  src/components/Loading/Loading.tsx
  src/components/common/Button.tsx
  src/components/common/button/Button.tsx
  src/components/common/header/Header.tsx
  src/components/common/icon/Icon.tsx
  src/components/common/icon/Icons.tsx
  src/components/common/index.tsx
  src/components/common/inputbox/input/Input.tsx
  src/components/common/inputbox/input/InputType.ts
  src/components/common/inputbox/select/Select.tsx
  src/components/common/inputbox/select/SelectType.ts
  src/components/common/label/Label.tsx
  src/components/common/spacing/Spacing.tsx
  src/components/layout/Layout.tsx
  src/index.css
  src/libs/api/children/ChildrenApi.ts
  src/libs/api/children/ChildrenType.ts
  src/libs/api/index.ts
  src/libs/api/queryClient.ts
  src/main.tsx
  src/pages/EditChildren/EditChildren.tsx
  src/pages/EditChildren/EditingChildren.tsx
  src/pages/home/HomePage.tsx
  src/routes/index.tsx
Labels: feat

#82 로그인 페이지 & 카카오 로그인 구현
  src/api/autorization/LoginApi.ts
  src/api/autorization/index.ts
  src/constants/common.ts
  src/constants/env.ts
  src/constants/index.ts
  src/libs/api/index.ts
  src/pages/home/HomePage.tsx
  src/pages/login/LoginPage.tsx
  src/routes/index.tsx
Labels: feat

#87 onboarding page개발
  src/api/onboarding.ts
  src/components/common/inputbox/input/Input.tsx
  src/components/common/inputbox/select/Select.tsx
  src/components/common/inputbox/select/SelectType.ts
  src/pages/onboarding/OnbardingPage.tsx
  src/pages/onboarding/constants.ts
  src/pages/onboarding/validate.ts
  src/routes/index.tsx
Labels: feat

#91 hotfix: 아이 정보 수정되지 않는 현상 개선
  src/components/common/inputbox/select/SelectType.ts
  src/pages/EditChildren/EditChildren.tsx
  src/pages/EditChildren/EditingChildren.tsx
Labels: feat

#116 feat: 아이 학원 정보 보기 대시보드 생성
  src/components/academy/SelectMyChlid.tsx
  src/components/common/navigationbar/NavigationBar.tsx
  src/libs/store/childInfoAtom.tsx
  src/pages/academy/AcademyDashboard.tsx
  src/pages/home/HomePage.tsx
  src/routes/index.tsx
Labels: feat

#124 chore: like Icon 추가, listRow onClick 수정
  src/assets/icon/Save.svg
  src/assets/icon/index.tsx
  src/components/common/icon/Icons.tsx
  src/components/common/listRow/ListRow.tsx
Labels: refac

#122 feat: 학원 시간 입력하기
  package-lock.json
  package.json
  src/components/academy/CustomTimePicker.tsx
  src/components/academy/SelectMyChlid.tsx
  src/components/academy/SelectTime.tsx
  src/components/common/inputbox/input/Input.tsx
  src/components/common/inputbox/input/InputType.ts
  src/components/common/inputbox/select/Select.tsx
  src/components/common/inputbox/select/SelectType.ts
  src/components/common/label/Label.tsx
  src/components/common/listRowSelect/ListRowSelect.tsx
  src/components/common/selectweek/Select.stories.tsx
  src/components/common/selectweek/SelectWeek.tsx
  src/hooks/index.ts
  src/libs/api/academy/AcademyApi.ts
  src/libs/api/academy/AcademyType.ts
  src/libs/api/index.ts
  src/libs/api/mapapi/mapApiType.ts
  src/libs/api/queryClient.ts
  src/libs/hooks/index.ts
  src/libs/hooks/useDebounce.ts
  src/libs/hooks/useModal.tsx
  src/libs/hooks/useSteps.ts
  src/libs/store/academyInfo.tsx
  src/pages/academy/AcademyDashboard.tsx
  src/pages/academy/AddSchedule/AddAcademyInfo.tsx
  src/pages/academy/AddSchedule/AddAcademyName.tsx
  src/pages/academy/AddSchedule/AddMemo.tsx
  src/pages/academy/AddSchedule/AddPayment.tsx
  src/pages/academy/AddSchedule/AddSchedule.tsx
  src/pages/academy/AddSchedule/index.tsx
  src/pages/selectcity/SelectCity.tsx
  src/routes/index.tsx
  src/styles/index.css
  tailwind.config.js
Labels: feat

#144 [Bug]: academyInfo Atom TypeError 개선
  src/libs/api/academy/AcademyType.ts
  src/libs/store/academyInfo.tsx
  src/pages/academy/AddSchedule/AddSchedule.tsx
Labels: bug

#146 [Refac]: 학원 정보 찾기 무한 스크롤
  package-lock.json
  package.json
  src/components/common/inputbox/input/Input.tsx
  src/libs/api/academy/AcademyApi.ts
  src/libs/store/academyInfo.tsx
  src/pages/academy/AddSchedule/AddAcademyName.tsx
  src/pages/academy/AddSchedule/AddSchedule.tsx
  src/pages/academy/AddSchedule/index.tsx
  src/pages/onboarding/OnbardingPage.tsx
Labels: refac

#147 [Feat]: 학원 정보 등록시 금액, 메모 입력
  src/components/common/button/Button.tsx
  src/components/common/button/ButtonType.ts
  src/components/common/button/constants.ts
  src/components/common/inputbox/select/Select.tsx
  src/components/common/inputbox/select/SelectType.ts
  src/components/common/listRowSelect/ListRowSelect.tsx
  src/libs/api/academy/AcademyApi.ts
  src/libs/api/academy/AcademyType.ts
  src/libs/store/academyInfo.tsx
  src/libs/utils/dateParse.ts
  src/pages/academy/AddSchedule/AddAcademyInfo.tsx
  src/pages/academy/AddSchedule/AddAcademyName.tsx
  src/pages/academy/AddSchedule/AddMemo.tsx
  src/pages/academy/AddSchedule/AddPayment.tsx
  src/pages/academy/AddSchedule/AddSchedule.tsx
  src/pages/academy/AddSchedule/index.tsx
Labels: feat

#129 세팅 탭에 있는 페이지 기능 개발
  src/components/common/header/Header.tsx
  src/components/common/inputbox/input/Input.tsx
  src/components/common/inputbox/input/InputType.ts
  src/components/common/inputbox/select/Select.tsx
  src/components/common/profile/Profile.tsx
  src/components/common/profile/ProfileType.ts
  src/libs/api/autorization/LoginApi.ts
  src/libs/api/autorization/logout/LogoutApi.ts
  src/libs/api/autorization/refresh/refreshApi.ts
  src/libs/api/autorization/refresh/refreshType.ts
  src/libs/api/index.ts
  src/libs/api/likeacademy/LikeAcademyApi.ts
  src/libs/api/likeacademy/LikeAcademyType.ts
  src/libs/api/mypage/myPageApi.ts
  src/libs/api/mypage/myPageType.ts
  src/libs/api/onboarding/onboardingApi.ts
  src/libs/api/onboarding/onboardingType.ts
  src/libs/store/likeacademyAtom.tsx
  src/libs/store/myPageAtom.tsx
  src/libs/store/onboardingAtom.tsx
  src/libs/utils/storage.ts
  src/pages/home/HomePage.tsx
  src/pages/likeAcademy/LikeAcademy.tsx
  src/pages/login/LoginPage.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/onboarding/OnbardingPage.tsx
  src/pages/onboarding/constants.ts
  src/pages/onboarding/validate.ts
  src/pages/setting/SettingPage.tsx
  src/routes/index.tsx
Labels: feat

#158 [Feat]: dashboard 상세보기 뷰 구현
  src/components/academy/SelectMyChlid.tsx
  src/components/common/inputbox/input/Input.tsx
  src/components/common/inputbox/select/Select.tsx
  src/components/common/label/LabelType.ts
  src/components/common/scheduleBox/ScheduleBox.tsx
  src/components/common/scheduleBox/ScheduleBoxType.ts
  src/components/selectcity/SelectCityStep2.tsx
  src/libs/api/academy/AcademyApi.ts
  src/libs/api/academy/AcademyType.ts
  src/libs/api/dashboard/DashBoardApi.ts
  src/libs/api/dashboard/DashBoardType.ts
  src/libs/store/academyInfo.tsx
  src/libs/utils/dateParse.ts
  src/libs/utils/weekParse.ts
  src/pages/academy/AcademyDashboard.tsx
  src/pages/academy/AcademyDetail.tsx
  src/pages/academy/AddSchedule/AddAcademyInfo.tsx
  src/pages/academy/AddSchedule/AddPayment.tsx
  src/routes/index.tsx
Labels: feat

#163 구글 로그인 구현
  src/constants/env.ts
  src/libs/api/autorization/LoginApi.ts
  src/libs/api/index.ts
  src/pages/login/LoginPage.tsx
  src/pages/login/constants.ts
  src/pages/setting/SettingPage.tsx
Labels: feat

#164 [Feat] : 아카데미 상세보기, 삭제하기 구현
  src/components/common/accordion/Accordion.tsx
  src/components/common/header/Header.tsx
  src/components/common/scheduleBox/ScheduleBox.tsx
  src/components/common/scheduleBox/ScheduleBoxType.ts
  src/libs/api/academy/AcademyType.ts
  src/libs/api/dashboard/DashBoardType.ts
  src/libs/store/academyInfo.tsx
  src/pages/academy/AcademyDashboard.tsx
  src/pages/academy/AcademyDetail.tsx
  src/pages/academy/AddSchedule/index.tsx
  src/pages/academy/academyDetail/AcademyDetailClass.tsx
  src/pages/academy/academyDetail/AcademyDetailHeader.tsx
  src/pages/academy/academyDetail/AcademyDetailMemo.tsx
  src/pages/academy/academyDetail/AcademyDetailPayment.tsx
  src/pages/academy/academyDetail/AcademySetting.tsx
  src/pages/academy/academyDetail/index.tsx
  src/routes/index.tsx
Labels: feat

#165 Refactor: SelectCity 리펙토링
  src/components/common/header/Header.tsx
  src/components/common/header/HeaderType.ts
  src/components/common/inputbox/select/Select.tsx
  src/components/selectcity/CityStep.tsx
  src/components/selectcity/SelectCityStep1.tsx
  src/components/selectcity/SelectCityStep2.tsx
  src/components/selectcity/SelectCityStep3.tsx
  src/components/selectcity/selectCityType.ts
  src/libs/api/mapapi/mapApi.ts
  src/libs/api/mapapi/mapApiType.ts
  src/libs/store/mapInfoAtom.ts
  src/pages/filter/FilterPage.tsx
  src/pages/selectcity/SelectCity.tsx
  src/pages/selectcity/constants.ts
  src/routes/index.tsx
  src/styles/index.css
  src/types/selectcity.ts
Labels: refac

#166 로그인 로고 구현
  src/libs/api/index.ts
  src/pages/login/LoginPage.tsx
Labels: feat

#176 /edit/{childId}랜더링 문제
  src/libs/api/mypage/myPageType.ts
  src/pages/EditChildren/EditingChildren.tsx
  src/pages/mypage/MyPage.tsx
Labels: bug

#177 [Feat]: 학원 정보 리뷰 남기기
  .eslintrc.cjs
  package-lock.json
  package.json
  src/components/common/toast/index.tsx
  src/components/review/ReviewBottomSheet.tsx
  src/libs/api/review/reviewApi.ts
  src/libs/api/review/reviewType.ts
  src/libs/hooks/useToastify.ts
  src/pages/academy/AcademyDashboard.tsx
  src/pages/academy/AddSchedule/AddPayment.tsx
  src/pages/academy/academyDetail/AcademyDetailHeader.tsx
  src/pages/academy/academyDetail/AcademySetting.tsx
Labels: feat

#182 아이 프로필사진 기본이미지 변경(아구몬 => 기본 이미지)
  src/components/common/informationBox/InformationBox.tsx
  src/components/common/informationBox/InformationBoxType.ts
  src/libs/api/children/ChildrenType.ts
  src/libs/api/mypage/myPageType.ts
  src/pages/home/HomePage.tsx
  src/pages/mypage/MyPage.tsx
Labels: refac

#179 [Feat]: 스케쥴 생성하기 기능
  src/components/common/inputbox/select/Select.tsx
  src/components/common/inputbox/select/SelectType.ts
  src/components/dashboard/SelectChild.tsx
  src/components/schedule/SelectAttendanceDate.tsx
  src/libs/api/schedule/scheduleApi.ts
  src/libs/api/schedule/scheduleType.ts
  src/libs/store/scheduleInfo.tsx
  src/pages/schedule/new/AddScheduleAcademy.tsx
  src/pages/schedule/new/AddScheduleMemo.tsx
  src/pages/schedule/new/AddScheduleTime.tsx
  src/pages/schedule/new/index.tsx
  src/routes/index.tsx
Labels: feat

#195 스케줄 디테일 부분
  src/components/common/header/Header.tsx
  src/libs/api/academy/scheduleDetail/ScheduleDetailApi.ts
  src/libs/api/academy/scheduleDetail/ScheduleDetailType.ts
  src/pages/academy/detailSchedule/DetailSchedulePage.tsx
  src/routes/index.tsx
Labels: refac

#198 [Feat]: 온보딩 progress Bar 작업
  package-lock.json
  src/components/common/progressBar/ProgressBar.stories.tsx
  src/components/common/progressBar/ProgressBar.tsx
  src/components/common/slider/Slider.stories.tsx
  src/components/common/slider/Slider.tsx
  src/pages/onboarding/OnbardingPage.tsx
  src/pages/schedule/new/index.tsx
Labels: bug, feat

#199 fix: build 에러 고치기
  src/components/common/bottomsheet/BottomSheet.stories.tsx
  src/components/common/informationBox/Information.stories.tsx
  src/components/common/inputbox/select/Select.stories.tsx
  src/components/common/slider/Slider.stories.tsx
  src/libs/store/childInfoAtom.tsx
  src/libs/store/myPageAtom.tsx
  src/libs/utils/dateParse.ts
  src/pages/academy/AcademyDashboard.tsx
  src/pages/academy/AddSchedule/AddMemo.tsx
  src/pages/academy/AddSchedule/index.tsx
  src/pages/academy/academyDetail/AcademySetting.tsx
  src/pages/calendar/CalendarPage.tsx
  src/pages/likeAcademy/LikeAcademy.tsx
  src/pages/schedule/new/AddScheduleTime.tsx
  src/pages/schedule/new/index.tsx
Labels: bug

#228 [Feat] : 슬라이더 바 제작
  src/components/common/progressBar/ProgressBar.tsx
  src/components/common/slider/Slider.tsx
Labels: feat

#229 likeAcademy 버그 수정
  src/pages/likeAcademy/LikeAcademy.tsx
  src/pages/setting/SettingPage.tsx
Labels: bug

#230 [Feat] : Toast UI 생성
  src/App.tsx
  src/components/common/header/Header.tsx
  src/components/common/toast/index.tsx
  src/components/layout/Layout.tsx
  src/components/review/ReviewBottomSheet.tsx
  src/libs/api/index.ts
  src/pages/academy/AcademyDashboard.tsx
  src/pages/academy/academyDetail/AcademySetting.tsx
  src/pages/academy/addSchedule/index.tsx
  src/pages/academy/editAcademy/index.tsx
  src/pages/home/HomePage.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/onboarding/OnbardingPage.tsx
  src/pages/schedule/new/index.tsx
Labels: feat

#232 홈페이지 sidebar overflow되는 문제
  src/pages/home/HomePage.tsx
  src/pages/likeAcademy/LikeAcademy.tsx
Labels: bug

#243 fix: 마이페이지 리액트 쿼리 적용
  src/libs/api/mypage/myPageApi.ts
  src/pages/mypage/MyPage.tsx
Labels: refac

#248 main머지
  package-lock.json
  src/components/common/inputbox/input/Input.tsx
  src/components/common/scheduleBox/ScheduleBox.tsx
  src/components/schedule/SelectAttendanceDate.tsx
  src/libs/api/dashboard/DashBoardType.ts
  src/libs/api/index.ts
  src/libs/api/mypage/myPageApi.ts
  src/libs/api/queryClient.ts
  src/libs/api/schedule/scheduleApi.ts
  src/libs/api/schedule/scheduleType.ts
  src/libs/store/scheduleInfo.tsx
  src/pages/academy/AcademyDashboard.tsx
  src/pages/academy/AddSchedule/index.tsx
  src/pages/academy/editAcademy/index.tsx
  src/pages/home/HomePage.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/onboarding/OnbardingPage.tsx
  src/pages/onboarding/validate.ts
  src/pages/schedule/edit/EditScheuleAcademy.tsx
  src/pages/schedule/edit/index.tsx
  src/pages/schedule/new/AddScheduleAcademy.tsx
  src/pages/schedule/new/AddScheduleMemo.tsx
  src/pages/schedule/new/AddScheduleTime.tsx
  src/pages/schedule/new/index.tsx
  src/routes/index.tsx
  tailwind.config.js
Labels: bug

#260 fix: 네비게이션바를 선택 했을때 이동이 안되는 문제 수정
  src/components/common/navigationbar/NavigationBar.tsx
  src/styles/index.css
Labels: bug

#258 fix: homepage scroll error해결
  src/pages/home/HomePage.tsx
Labels: bug

#256 fix: EditChildren page 아이 default image 변경(아구몬❌)
  src/components/common/profile/Profile.tsx
  src/pages/EditChildren/EditChildren.tsx
  src/pages/mypage/MyPage.tsx
Labels: bug

#257 hotfix: 필터 구현
  src/components/common/slider/Slider.stories.tsx
  src/components/common/slider/Slider.tsx
  src/libs/store/mapFilterAtom.ts
  src/pages/filter/FilterPage.tsx
Labels: bug
