Repository Guzzing/Studay_Client, pull requests merged in 2023-12, with the labels that each got.

#268 회원 탈퇴 구현
  src/libs/api/autorization/withdrawUser/withdrawUserApi.ts
  src/libs/utils/storage.ts
  src/pages/academy/AcademyDashboard.tsx
  src/pages/login/LoginPage.tsx
  src/pages/map/MapPage.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/onboarding/OnbardingPage.tsx
Labels: bug, feat

#261 [Refac] : 대시보드 관련한 QA 반영
  src/components/academy/SelectTime.tsx
  src/components/common/button/Button.tsx
  src/components/common/header/Header.tsx
  src/components/common/inputbox/select/Select.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/scheduleBox/ScheduleBox.tsx
  src/components/common/selectweek/SelectWeek.tsx
  src/components/dashboard/SelectChild.tsx
  src/components/dashboard/SelectLesson.tsx
  src/pages/academy/AcademyDashboard.tsx
  src/pages/academy/addSchedule/AddAcademyInfo.tsx
  src/pages/academy/addSchedule/AddAcademyName.tsx
  src/pages/academy/addSchedule/AddPayment.tsx
  src/pages/academy/addSchedule/AddSchedule.tsx
  src/pages/academy/addSchedule/index.tsx
  src/pages/academy/editAcademy/index.tsx
  src/routes/index.tsx
  src/styles/index.css
Labels: refac

#279 마이페이지 pull 에러 수정
  src/pages/mypage/MyPage.tsx
Labels: bug

#288 [Feat]: 프로필 사진 변경 기능, 설정 페이지에서 아이 상세보기 페이지 이동
  src/components/common/profile/Profile.tsx
  src/components/common/profile/ProfileType.ts
  src/libs/api/children/ChildrenType.ts
  src/pages/EditChildren/EditChildren.tsx
  src/pages/EditChildren/EditingChildren.tsx
  src/pages/mypage/MyPage.tsx
  src/routes/index.tsx
Labels: bug

#291 fix: 마이페이지 버그 수정
  src/pages/mypage/MyPage.tsx
Labels: bug

#301 온보딩 selectbox 기본값 설정
  src/components/common/button/Button.tsx
  src/components/common/inputbox/input/Input.tsx
  src/pages/onboarding/OnbardingPage.tsx
  src/pages/onboarding/constants.ts
Labels: bug

#302 [Bug] : 아이 사진 수정 정보가 바로 반영 안되는 현상 해결
  src/components/common/header/Header.tsx
  src/components/common/profile/Profile.tsx
  src/components/common/toast/index.tsx
  src/pages/EditChildren/EditChildren.tsx
  src/pages/EditChildren/EditingChildren.tsx
  src/routes/index.tsx
Labels: bug

#303 [Bug] : Dashboard 관련 2차 QA 수정사항 반영
  package-lock.json
  package.json
  src/components/BottomSheet/Dimmer.tsx
  src/components/common/label/LabelType.ts
  src/components/common/scheduleBox/ScheduleBox.tsx
  src/components/common/scheduleBox/ScheduleBoxType.ts
  src/components/review/ReviewBottomSheet.tsx
  src/libs/api/academy/AcademyType.ts
  src/libs/api/dashboard/DashBoardApi.ts
  src/libs/api/dashboard/DashBoardType.ts
  src/libs/hooks/useOutSideClick.ts
  src/pages/academy/AcademyDashboard.tsx
  src/pages/academy/academyDetail/AcademyDetailClass.tsx
  src/pages/academy/academyDetail/AcademyDetailHeader.tsx
  src/pages/academy/academyDetail/AcademySetting.tsx
  src/pages/academy/addSchedule/AddAcademyInfo.tsx
  src/pages/academy/addSchedule/AddAcademyName.tsx
  src/pages/academy/addSchedule/index.tsx
  src/routes/index.tsx
Labels: bug

#309 [Refac]: schedule 생성, 수정 validation 추가
  src/components/Loading/Loading.tsx
  src/components/academy/CustomTimePicker.tsx
  src/components/common/button/Button.tsx
  src/components/common/calender/Calender.stories.tsx
  src/components/common/modal/Modal.tsx
  src/components/schedule/SelectAttendanceDate.tsx
  src/libs/api/children/ChildrenType.ts
  src/libs/api/dashboard/DashBoardApi.ts
  src/libs/api/filter/filterApi.ts
  src/libs/api/index.ts
  src/libs/api/mapapi/mapApi.ts
  src/libs/api/onboarding.ts
  src/libs/api/schedule/scheduleType.ts
  src/libs/store/childInfoAtom.tsx
  src/libs/store/scheduleInfo.tsx
  src/libs/utils/date.ts
  src/libs/utils/scheduleParse.ts
  src/libs/utils/storage.ts
  src/pages/academy/AcademyDashboard.tsx
  src/pages/academy/detailSchedule/DetailScheduleHeader.tsx
  src/pages/academy/detailSchedule/DetailSchedulePage.tsx
  src/pages/home/HomePage.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/schedule/edit/EditScheuleAcademy.tsx
  src/pages/schedule/edit/index.tsx
  src/pages/schedule/new/AddScheduleAcademy.tsx
  src/pages/schedule/new/AddScheduleTime.tsx
  src/pages/schedule/new/index.tsx
Labels: refac

#312 [Bug] : 프로필 이미지 수정 로직 개선
  src/components/common/profile/Profile.tsx
  src/libs/api/children/ChildrenApi.ts
  src/pages/EditChildren/EditChildren.tsx
  src/pages/EditChildren/EditingChildren.tsx
  src/pages/home/HomePage.tsx
Labels: bug

#328 [Feat]: meta 태그, manifest 세팅 추가
  index.html
  public/icon.png
  public/manifest.json
  src/pages/academy/AcademyDashboard.tsx
  src/pages/login/LoginPage.tsx
Labels: feat

#326 스케줄 detail 겹치는 문제 + 온보딩 버튼 안 보이는 문제 해결
  src/components/common/button/Button.tsx
  src/components/common/button/ButtonType.ts
  src/pages/academy/detailSchedule/DetailScheduleHeader.tsx
  src/pages/academy/detailSchedule/DetailSchedulePage.tsx
  src/pages/likeAcademy/LikeAcademy.tsx
  src/pages/onboarding/OnbardingPage.tsx
Labels: bug

#338 fix: schedule detail page불필요한 border제거
  src/pages/academy/detailSchedule/DetailSchedulePage.tsx
Labels: bug
